name: SonarCloud Analysis
on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build and analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Для интеграции с GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Токен из SonarCloud
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=your-project-key \
            -Dsonar.organization=your-org-name \
            -Dsonar.host.url=https://sonarcloud.io