name: SonarCloud
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Analyze with SonarCloud
        run: |
          mvn -B verify org.jacoco:jacoco-maven-plugin:report sonar:sonar \
            -Dsonar.projectKey=Bank \
            -Dsonar.organization=SAFA \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${SONAR_TOKEN}
        env:
          GITHUB_TOKEN: ${SONAR_TOKEN}